[package]
name = "aocode"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
regex = "1.11.1"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "aocbench"
harness = false
